@hostname = localhost
@port = 5000
@host = http://{{hostname}}:{{port}}
@store = Apple Store
### Check health of the service
GET {{host}}/healthz/status
### List all the stores
GET {{host}}/stores
### Create a store
POST  {{host}}/stores
Content-Type: application/json

{"name": "{{store}}"}
### Get a store
GET {{host}}/stores/{{store}}
### Create item in a store
POST {{host}}/stores/{{store}}/items
Content-Type: application/json

{"name": "Table","price": 2099}
### Get the items from a store
GET {{host}}/stores/{{store}}/items

